#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VERSION="${1:-}"
ARM_ARCHIVE="${2:-}"
INTEL_ARCHIVE="${3:-}"
OUTPUT="${4:-$ROOT/dist/Casks/space-mesh.rb}"

if [[ -z "$VERSION" || -z "$ARM_ARCHIVE" || -z "$INTEL_ARCHIVE" ]]; then
  echo "Usage: $0 <version> <arm64-zip> <x86_64-zip> [output-cask]" >&2
  exit 2
fi

for archive in "$ARM_ARCHIVE" "$INTEL_ARCHIVE"; do
  if [[ ! -f "$archive" ]]; then
    echo "ERROR: release archive not found: $archive" >&2
    exit 1
  fi
done

ARM_SHA="$(shasum -a 256 "$ARM_ARCHIVE" | awk '{print $1}')"
INTEL_SHA="$(shasum -a 256 "$INTEL_ARCHIVE" | awk '{print $1}')"
mkdir -p "$(dirname "$OUTPUT")"

cat >"$OUTPUT" <<EOF
# This file is generated by the space-mesh release workflow. DO NOT EDIT.
cask "space-mesh" do
  version "$VERSION"

  on_arm do
    sha256 "$ARM_SHA"

    url "https://github.com/x-mesh/space-mesh/releases/download/v#{version}/space-mesh-macos-#{version}-arm64.zip"
  end
  on_intel do
    sha256 "$INTEL_SHA"

    url "https://github.com/x-mesh/space-mesh/releases/download/v#{version}/space-mesh-macos-#{version}-x86_64.zip"
  end

  name "space-mesh"
  desc "Disk space analyzer with treemap, cleanup guidance, and incremental scanning"
  homepage "https://github.com/x-mesh/space-mesh"

  livecheck do
    url :url
    strategy :github_latest
  end

  depends_on macos: :sonoma

  app "space-mesh.app"
  binary "#{appdir}/space-mesh.app/Contents/Resources/space-mesh"

  preflight do
    system_command "/usr/bin/osascript",
                   args:         ["-e", 'tell application "space-mesh" to quit'],
                   must_succeed: false
  end

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/space-mesh.app"],
                   sudo: false
  end

  zap trash: [
    "~/Library/Application Support/space-mesh",
    "~/Library/Preferences/com.x-mesh.space-mesh.plist",
    "~/Library/Saved Application State/com.x-mesh.space-mesh.savedState",
  ]

  caveats <<~CAVEATS
    space-mesh is distributed with ad-hoc signing and without Apple notarization.
    This cask removes the quarantine attribute after installation.

    The bundled space-mesh CLI is linked to #{HOMEBREW_PREFIX}/bin.
  CAVEATS
end
EOF

echo "==> Cask generated: $OUTPUT"
echo "    arm64  $ARM_SHA"
echo "    x86_64 $INTEL_SHA"
